bmp2nes gfx/sprites/rockman/rockman.bmp
bmp2nes gfx/sprites/weapons/charge_shot.bmp
bmp2nes gfx/sprites/bars/bar_vertical.bmp
bmp2nes gfx/sprites/weapons/rock_buster.bmp
bmp2nes gfx/sprites/capsules/small_weapon_capsule.bmp
bmp2nes gfx/sprites/tanks/e_tank.bmp
bmp2nes gfx/sprites/capsules/large_life_capsule.bmp
bmp2nes gfx/sprites/capsules/small_life_capsule.bmp
bmp2nes gfx/sprites/capsules/large_weapon_capsule.bmp
bmp2nes gfx/sprites/explosion.bmp
bmp2nes gfx/sprites/1up.bmp
bmp2nes gfx/sprites/ready.bmp
bmp2nes gfx/sprites/tanks/blank_tank.bmp
bmp2nes gfx/sprites/rockman/pow.bmp
bmp2nes gfx/sprites/rockman/jet.bmp
bmp2nes gfx/sprites/menus/animations/rockman_to_jet.bmp
bmp2nes gfx/sprites/menus/animations/rockman_to_pow.bmp
bmp2nes gfx/sprites/menus/animations/jet_to_pow.bmp
bmp2nes gfx/sprites/menus/animations/pow_to_jet.bmp
bmp2nes gfx/sprites/enemies/rounder_ii.bmp
bmp2nes gfx/sprites/zakos/zako_dot.bmp
bmp2nes gfx/sprites/zakos/1.bmp
bmp2nes gfx/sprites/enemies/shield_attacker_gtr.bmp
bmp2nes gfx/fill/black.bmp
bmp2nes gfx/sprites/enemies/teck.bmp
bmp2nes gfx/fill/teck.bmp
bmp2nes gfx/sprites/enemies/cannopeller.bmp
bmp2nes gfx/sprites/enemies/brown.bmp
bmp2nes gfx/sprites/enemies/tank_csii.bmp
asm6 main.asm rm6.nes
@pause